# Generated by Django 3.0.8 on 2020-12-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price_sum',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сумма'),
        ),
    ]
