# Generated by Django 3.0.8 on 2020-12-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201204_2247'),
        ('cart', '0002_cart_price_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(blank=True, to='products.Product', verbose_name='Товары'),
        ),
    ]
