# Generated by Django 3.0.8 on 2020-12-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20201205_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price_sum',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Сумма'),
        ),
    ]
