# Generated by Django 3.0.8 on 2020-12-02 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('secondary_objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Название')),
                ('main_img', models.ImageField(upload_to='main_product_images', verbose_name='Главное изображение')),
                ('usd_price', models.PositiveSmallIntegerField(verbose_name='Цена, $')),
                ('published', models.DateField(verbose_name='Опубликована')),
                ('pages_number', models.PositiveSmallIntegerField(verbose_name='Кол-во страниц')),
                ('cover', models.CharField(max_length=35, verbose_name='Переплёт')),
                ('format', models.CharField(max_length=25, verbose_name='Формат')),
                ('isbn', models.CharField(max_length=19, verbose_name='ISBN')),
                ('weight_gr', models.PositiveSmallIntegerField(verbose_name='Вес, г')),
                ('age_restriction', models.PositiveSmallIntegerField(choices=[(0, '0+'), (6, '6+'), (12, '12+'), (16, '16+'), (18, '18+')], verbose_name='Возрастное ограничение')),
                ('books_available', models.PositiveSmallIntegerField(verbose_name='Книг в наличии')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Рейтинг')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('authors', models.ManyToManyField(to='secondary_objects.Author', verbose_name='Авторы')),
                ('book_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='secondary_objects.BookSeries', verbose_name='Серия')),
                ('genres', models.ManyToManyField(related_name='books', to='secondary_objects.Genre', verbose_name='Жанры')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='secondary_objects.Publisher', verbose_name='Издательство')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='products.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comment', to='products.Product', verbose_name='Товар')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Комментарий к товару',
                'verbose_name_plural': 'Коментарии к товарам',
            },
        ),
    ]
