# Generated by Django 3.0.8 on 2020-12-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0003_auto_20201204_2108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RatingMarks',
            new_name='RatingMark',
        ),
    ]
