# Generated by Django 3.0.8 on 2020-12-04 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201204_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating_marks',
        ),
        migrations.AddField(
            model_name='productcomment',
            name='rate',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RatingMark',
        ),
    ]
