# Generated by Django 3.0.8 on 2020-12-04 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_method', models.PositiveSmallIntegerField(choices=[(1, 'Самовывоз'), (2, 'Доставка')], verbose_name='Способ получения')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Заказ принят. Идет обработка заказа.'), (2, 'Заказ ожидает в пункте выдачи.'), (3, 'Посылка принята.'), (4, 'В пути.'), (5, 'Заказ доставлен.'), (6, 'Заказ выполнен.')], verbose_name='Статус заказа')),
                ('byn_price', models.PositiveSmallIntegerField(verbose_name='Цена, бел. рубли')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.Cart', verbose_name='Корзина')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='users.Profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_comment', to='order.Order', verbose_name='Заказ')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_comment', to='users.Profile', verbose_name='Профлиль')),
            ],
            options={
                'verbose_name': 'Комментарий к заказу',
                'verbose_name_plural': 'Коментарии к заказам',
            },
        ),
    ]
