# Generated by Django 3.0.8 on 2020-11-25 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('code', models.PositiveSmallIntegerField(verbose_name='Код страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название города')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondary_objects.Country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_and_house', models.CharField(max_length=200, verbose_name='Улица, дом, кв')),
                ('postcode', models.CharField(max_length=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=18)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=18)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondary_objects.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
