# Generated by Django 3.0.8 on 2020-12-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='default_profile.jpg', upload_to='authors', verbose_name='Фото'),
        ),
    ]
